name: CI

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        docker build -t soriano-dev/docker-registry-github:latest -f Dockerfile .
        docker tag soriano-dev/docker-registry-github:latest soriano-dev/docker-registry-github:${{ github.sha }}
    
    - run: |
        docker push soriano-dev/docker-registry-github:latest
        docker push soriano-dev/docker-registry-github:${{ github.sha }}
