name: CI

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        docker-compose up -d
        docker tag dockerized-node:latest dockerized-node:${{ github.sha }}
    
    - run: |
        docker push dockerized-node:latest
        docker push dockerized-node:${{ github.sha }}
